config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  #devise_scope :user do
  #  # Redirects signing out users back to sign-in
  #  get "users", to: "devise/sessions#new"
  #end

  devise_for :users, only: [:session, :registration]
  
  resources :questions do
    resources :answers, except: [:index, :show]
  end

  # Defines the root path route ("/")
  root "application#redirect"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  scope :ordered, -> { order(id: :desc) }

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user
  
  scope :ordered, -> { order(id: :desc) }

  validates :body, :title, presence: true
end

app/models/search.rb
class Search

  def self.perform(search_term)
    return [] if search_term.nil? || search_term.empty?

    questions = Question.where("title like ? or body like ?", "%#{search_term}%", "%#{search_term}%")
    question_answers = Answer.where("body like ?", "%#{search_term}%").collect(&:question)

    (questions + question_answers).sort.uniq
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :registerable
  has_many :answers
  has_many :questions
         
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question
  before_action :set_answer, only: %i[edit update destroy]

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(answer_params)

    if @answer.save
      respond_to do |format|
        format.html { redirect_to question_path(@question), notice: "Posted your answer!" }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @answer.update(answer_params) && @answer.user_id == current_user.id
      redirect_to question_path(@question), notice: "Updated your answer"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @answer.user_id == current_user.id 
      @answer.destroy

      redirect_to @question, notice: "Your answer has been deleted"
    else
      redirect_to @question, alert: "You can only delete your own answers"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:body).merge(user_id: current_user.id)
  end

  def set_answer
    @answer = @question.answers.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:redirect]

  def redirect
    redirect_to questions_path
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_question, only: %i[show edit update destroy]

  def index
    if params[:search].present?
      @questions = Search.perform(params[:search])
    else
      @questions = Question.ordered
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      respond_to do |format|
        format.html { redirect_to questions_path, notice: "Your new question has been posted!" }
        format.turbo_stream
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @answers = @question.answers.ordered
  end

  def edit
  end

  def update
    if @question.update(question_params) && @question.user_id == current_user.id
      redirect_to questions_path, notice: "Updated your question"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @question.user_id == current_user.id
      @question.destroy

      respond_to do |format|
        format.html { redirect_to questions_path, notice: "Your question has been deleted" }
        format.turbo_stream
      end
    else
      redirect_to questions_path, alert: "You can only delete your owns questions"
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body).merge(user_id: current_user.id)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<%= turbo_frame_tag answer do %>
<div class="card block ml-6 mb-3">
    <div class="card-content">
      <div class="content">
        <%= answer.body %>
      </div>

      <div class="columns is-mobile">
        <div class="column is-italic">
          <%= answer.user.try(:email) %>
        </div>
        <div class="column">
          <% if current_user && current_user.id == answer.user_id %>
            <%= button_to "Delete", question_answer_path(answer.question, answer), method: :delete, class: "button is-danger is-outlined is-pulled-right" %>
            <%= link_to "Edit", edit_question_answer_path(answer.question, answer), class: "button is-info is-outlined is-pulled-right" %>
          <% end %>
        </div>
      </div>
      
    </div>
</div>
<% end %>

app/views/answers/_form.html.erb
<%= simple_form_for [question, answer], html: { class: "answer form" } do |f| %>

  <div class="card block">
    <% if answer.errors.any? %>
      <div class="error-message">
        <%= answer.errors.full_messages.to_sentence.capitalize %>
      </div>
      <% end %>

    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <%= @question.title %>
        </div>
      </div>

      <div class="content">
        <%= f.input :body, label: false %>
      </div>

      <%= f.submit class: "button is-primary has-text-weight-bold" %>
      <%= link_to "Cancel", questions_path, class: "button is-info" %>
    </div>
  </div>  
  
  
<% end %>

app/views/answers/create.turbo_stream.erb
<%= turbo_stream.prepend "answers", @answer %>
<%= turbo_stream.update Answer.new, "" %>

app/views/answers/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to question"), question_path(@question) %>

  <div class="header">
    <h1>Edit Answer</h1>
  </div>

  <%= turbo_frame_tag @answer do %>
    <section class="ml-6 block">
      <%= render "form", question: @question, answer: @answer %>
    </section>
  <% end %>
</main>

app/views/answers/new.html.erb
<section class="container">
  <%= link_to sanitize("&larr; Back to question"), @question %>

  <h1 class="title">New Answer</h1>
  
  <%= turbo_frame_tag @answer do %>
    <div class="block">
      <%= render "form", question: @question, answer: @answer %>
    </div>
  <% end %>
</section>

app/views/layouts/_flash.html.erb
<div class="container">
<% if notice %>
  <div class="notification is-success"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="notification is-danger"><%= alert %></div>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
<div class="navbar-brand">
  <%= link_to root_path do %> 
    <%= image_tag "answerme.png", size: "224x56" %>
  <% end %>

  <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
    <span aria-hidden="true"></span>
  </a>
</div>

<div id="navbarBasicExample" class="navbar-menu">
  <div class="navbar-start">
    <%= link_to "Home", root_path, class: "navbar-item" %>
    
    <%= link_to "Questions", questions_path, class: "navbar-item" %>
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        <% if current_user %>
          <%= button_to 'Log out', destroy_user_session_path, method: :delete, class:"button is-light" %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path, class:"button is-primary has-text-weight-bold" %>
          <%= link_to 'Log in', new_user_session_path, class:"button is-light" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnswerMe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= simple_form_for question, html: { class: "question form" } do |f| %>

  <div class="card block">
    <% if question.errors.any? %>
      <div class="error-message">
        <%= question.errors.full_messages.to_sentence.capitalize %>
      </div>
      <% end %>

    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <%= f.input :title, label: false, input_html: { autofocus: true, class: "title is-4" } %>
        </div>
      </div>

      <div class="content">
        <%= f.input :body, label: false %>
      </div>

      <%= f.submit class: "button is-primary has-text-weight-bold" %>
      <%= link_to "Cancel", questions_path, class: "button is-info" %>
    </div>
  </div>  
  
  
<% end %>

app/views/questions/_question.html.erb
<div class="card block">
<%= turbo_frame_tag question do %>
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <p>
            <%= link_to question.title,
                        question_path(question),
                        data: { turbo_frame: "_top" },
                        class: "title is-4" %>
          </p>
          <p class="subtitle is-6"><%= question.user.try(:email) %></p>
        </div>
      </div>

      <div class="content">
        <%= question.body %>
      </div>

      <div class="columns is-mobile">
        <div class="column">
          <%= link_to pluralize(question.answers.try(:count), "answer"), question_path(question),data: { turbo_frame: "_top" } %>
        </div>
        <div class="column">
          <% if current_user && current_user.id == question.user_id %>
            <%= button_to "Delete", question_path(question), method: :delete, class: "button is-danger is-outlined is-pulled-right" %>
            <%= link_to "Edit", edit_question_path(question), class: "button is-info is-outlined is-pulled-right" %>
          <% end %>
        </div>
      </div>
      
    </div>
<% end %>
</div>

app/views/questions/create.turbo_stream.erb
<%= turbo_stream.prepend "questions", @question %>
<%= turbo_stream.update Question.new, "" %>

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question %>

app/views/questions/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to question"), question_path(@question) %>

  <div class="header">
    <h1>Edit question</h1>
  </div>

  <%= turbo_frame_tag @question do %>
    <block>
    <%= render "form", question: @question %>
    </block>
  <% end %>
</main>

app/views/questions/index.html.erb
<section class="section">
  <div class="container">

    <%= turbo_frame_tag "function_turbo_frame" do %>

      <div class="columns is-mobile">
        <div class="column">
          <h1 class="title">Questions</h1>
        </div>
        <div class="column">
          <% if current_user %>
          <%= link_to "Ask a question",
                      new_question_path,
                      data: { turbo_frame: dom_id(Question.new) },
                      class: "button is-primary has-text-weight-bold is-pulled-right" %>
          <% else %>
          <%= link_to "Ask a question",
                      new_user_session_path,
                      data: { turbo_frame: "_top" },
                      class: "button is-primary has-text-weight-bold is-pulled-right" %>
          <% end %>
        </div>
      </div>

    <% end %>

    <%= turbo_frame_tag Question.new %>

    <%= turbo_frame_tag "questions" do %>
      <%= render @questions %>
    <% end %>
  </div>
</section>

app/views/questions/new.html.erb
<section class="container">
  <%= link_to sanitize("&larr; Back to questions"), questions_path %>

  <%# turbo_frame_tag "function_turbo_frame" do %>
    <h1 class="title">New question</h1>
  
  <%= turbo_frame_tag @question do %>
    <block>
      <%= render "form", question: @question %>
    </block>
  <% end %>
</section>

app/views/questions/show.html.erb
<section class="container">
  <block>
  <%= link_to sanitize("&larr; Back to questions"), questions_path %>
  </block>

  <div class="card block">
    <div class="card-content">
      <div class="media">
        <div class="media-content">
          <h1 class="title is-4">
            <%= @question.title %>
          </h1>
          <p class="subtitle is-6"><%= @question.user.try(:email) %></p>
        </div>
      </div>

      <div class="content">
        <%= @question.body %>
      </div>

      <%= link_to "Answer",
                  new_question_answer_path(@question),
                  data: { turbo_frame: dom_id(Answer.new) },
                  class: "button is-primary has-text-weight-bold" %>
      
    </div>
  </div>

  <div class="ml-6 mb-3 block">
    <%= turbo_frame_tag Answer.new %>
  </div>

  <%= turbo_frame_tag 'answers' do %>
    <%= render @answers, question: @question %>
  <% end %>
</section>